# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hash Viewer
author:
  name: "Matthew Wildrick Thomas"
  website: "https://mattwthomas.com"

tagline: "Share Math and Markdown"
description: >- # this means to ignore newlines until "baseurl:"
   You can use this to store entire documents in URLs. It is similar to [Hashify](https://hashify.me) but has a simpler presentation, uses LZ-based compression via [lz-string](https://github.com/pieroxy/lz-string), and supports LaTeX math input via [MathJaX](https://www.mathjax.org/). It is hosted on [GitHub Pages](https://pages.github.com/) and uses [marked](https://marked.js.org/) for markdown processing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hash.mwt.me" # the base hostname & protocol for your site, e.g. http://example.com

social:
  name: Hash Viewer
  links:
    - "https://github.com/mwt/hash-viewer"
    - "https://www.producthunt.com/posts/hash-viewer"
    - "https://angel.co/projects/1258295-hash-viewer"
    - "https://alternativeto.net/software/hash-viewer/about/"
    - "https://devmesh.intel.com/projects/hash-viewer"


# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-octicons
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
